@echo off
setlocal

set "PROJECT_DIR=%~dp0"
set "HITTEAM_URL=http://127.0.0.1:8765/index.html"
set "HITTEAM_API=http://127.0.0.1:8787/api/health"

powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$project=[System.IO.Path]::GetFullPath($env:PROJECT_DIR); $url=$env:HITTEAM_URL; $apiPort=8787; $webPort=8765; $pyLauncher=Get-Command py.exe -ErrorAction SilentlyContinue; $python=Get-Command python.exe -ErrorAction SilentlyContinue; if($pyLauncher){$file=$pyLauncher.Source; $prefix=@('-3')}elseif($python){$file=$python.Source; $prefix=@()}else{Add-Type -AssemblyName PresentationFramework; [System.Windows.MessageBox]::Show('Python 3 is required.','HiTeam startup failed')|Out-Null; exit 1}; if(-not(Get-NetTCPConnection -LocalPort $apiPort -State Listen -ErrorAction SilentlyContinue)){Start-Process -WindowStyle Hidden -FilePath $file -ArgumentList ($prefix+@('backend\server.py')) -WorkingDirectory $project}; if(-not(Get-NetTCPConnection -LocalPort $webPort -State Listen -ErrorAction SilentlyContinue)){Start-Process -WindowStyle Hidden -FilePath $file -ArgumentList ($prefix+@('-m','http.server',$webPort,'--bind','127.0.0.1')) -WorkingDirectory $project}; for($i=0;$i -lt 40;$i++){if((Get-NetTCPConnection -LocalPort $apiPort -State Listen -ErrorAction SilentlyContinue) -and (Get-NetTCPConnection -LocalPort $webPort -State Listen -ErrorAction SilentlyContinue)){break}; Start-Sleep -Milliseconds 100}; if(-not(Get-NetTCPConnection -LocalPort $apiPort -State Listen -ErrorAction SilentlyContinue)){Add-Type -AssemblyName PresentationFramework; [System.Windows.MessageBox]::Show('HiTeam auth backend failed to start. Check port 8787.','HiTeam startup failed')|Out-Null; exit 1}; if(-not(Get-NetTCPConnection -LocalPort $webPort -State Listen -ErrorAction SilentlyContinue)){Add-Type -AssemblyName PresentationFramework; [System.Windows.MessageBox]::Show('HiTeam web server failed to start. Check port 8765.','HiTeam startup failed')|Out-Null; exit 1}; Start-Process $url"

exit /b 0
